### ISSUE TITLE
python script available?

### ISSUE THREAD

**Issue by bbinet** [lvzon/soliviamonitor#1]
I'm also looking to monitor a Delta Solivia RPI inverter using the Delta serial protocol over RS485.
Any chance you could share the Python script you're talking about so that we may be able to share our efforts?

**Comment by lvzon** [comment]
I just added the script to the repository. It still needs quite a lot of work (see comments in the code), and I modified quite some things that I haven't tested yet, so it probably won't work directly. But maybe it's useful to you!

**Comment by bbinet** [comment]
Yes that is useful, thank you!

**Comment by lvzon** [comment]
At the very least, I expect that looking for '\x9d\x60\x01' won't work for all Delta RPI inverter models, as the length of the data structure seems to vary somewhat between models...

**Comment by bbinet** [comment]
Yes, on my side, I get '\xa0\x60\x01' which means 160bytes data length.

**Comment by lvzon** [comment]
Which model do you have?

**Comment by bbinet** [comment]
The model is  a RPI M8A inverter.

**Comment by lvzon** [comment]
Did you get anything to work with the RPI M8A? I've now fixed the code to work with the M15A and M20A, but eventually I'd like to support more inverter types...

**Comment by bbinet** [comment]
Not yet, but I may have some time to test it again soon.
