### ISSUE TITLE
soliviamonitor does not send any request (listening only)

### ISSUE THREAD

**Issue by bbinet** [lvzon/soliviamonitor#6]
I'm back to testing soliviamonitor on our RPI M8A inverter, but it seems soliviamonitor does not send any request on the RS485 bus, it only listen to incoming data in an infinite loop: https://github.com/lvzon/soliviamonitor/blob/master/soliviamonitor.py#L383-L384

Is it expected behavior? (I don't understand how the inverter could send any data on the RS485 wire if we don't send a request to it first)

**Comment by bbinet** [comment]
I tried to add the line `send_request(connection, 1, b'\x60\x01')` in the while loop (just before the `data = get_message(connection, 1.0)` line), and I'm now receiving some inverter data back from time to time:
the inverter only replies once in a while: this seems quite random, sometimes it replies once after 250 requests, sometimes once after 25 requests. Anyway, I don't know why the inverter does not reply to every request...
Any idea?

**Comment by bbinet** [comment]
I'm wondering if it could be due to a misconfigured rs485 port (I'm using your `unset_serial_ctrlchars.sh` script to configure the tty port though).

**Comment by lvzon** [comment]
Currently the code only sends a request if it hasn't received any inverter data for a specified period of time (`sampleinterval`, currently 60 seconds I think). I've not checked if this still works though. My setup has a Delta monitoring gateway attached tot the RS485-bus, which sends frequent information requests to the inverter, so I only need to listen (unless the Delta gateway stops working). Making extra calls to  `send_request()` should indeed solve this. :-) It's strange that the inverter doesn't always respond though. Maybe one request per second is too much? You could try adding a delay (or alternatively, remove the `send_request()` and set `sampleinterval` to a lower value). Indeed it could also be an issue with RS485, either with port configuration or with the physical setup (incorrect bus termination, unsuitable cable or a loose connection somewhere).  The `unset_serial_ctrlchars.sh`-script seems to work for me when it comes to receiving data, but I've not tried sending a lot of requests on the bus.

**Comment by bbinet** [comment]
I've rework the whole script in project which better meet my needs, see here: https://github.com/bbinet/delta-rpi

Thank you for the initial bits of code and protocol understanding that I've picked from your project.
